validation_venues = [
    "Black Sheep",
    "Blue Gate Music Hall", 
    "Blue Moon Bar and Grill", 
    "Blueberry Hill's Duck Room", 
    "Bluebird Theater", 
    "Bottom Of The Hill"
    ]

venues = [
    "1904",
    "123 Pleasant St.",
    "18 23 Mystery Bar",
    "1867 Bar",
    "191 Toole",
    "260 First",
    "40 Watt Club",
    "89 North Music Venue",
    "89th Street - OKC",
    "A&R Music Bar",
    "Ace Of Cups",
    "Acorn Center for the Performing Arts",
    "Agave",
    "Alberta Rose Theatre",
    "Alma Mater",
    "Amsterdam Bar and Hall",
    "Arts Center of Coastal Carolina",
    "At The Tabernacle",
    "Auburn State Theatre",
    "Backstage Bar & Billards (Triple B's)",
    "Bank Of NH Stage",
    "Barns At Wolf Trap",
    "Barrell & Vine",
    "Beachcomber Of Wellfleet",
    "Beachland Ballroom & Tavern",
    "Beachland Ballroom and Tavern",
    "Bearsville Theater",
    "Belly Up Aspen",
    "Chop Suey",
    "Bethesda Blues & Jazz Supper Club",
    "BFE Rock Club",
    "Big L Ranch",
    "Big Rob's",
    "Black Buzzard",
    "Black Sheep",
    "Blue Gate Music Hall",
    "Blue Light Live Lubbock",
    "Blue Moon Bar and Grill",
    "Blueberry Hill's Duck Room",
    "Bluebird Theater",
    "Bombyx Center For Arts & Equity",
    "Booth Playhouse",
    "Bottom Of The Hill",
    "Brick & Mortar",
    "Brick By Brick",
    "Bright Box",
    "Brighton Music Hall",
    "Broad Brook Opera House",
    "Bronze Peacock At House Of Blues",
    "Brooklyn Made",
    "Buck Owens' Crystal Palace",
    "Buffalo Iron Works",
    "Bull Run Restaurant",
    "Cambridge Room",
    "Cap City Comedy Club",
    "Capone's",
    "Captain's Getaway",
    "Cavalier Theatre And Lounge",
    "Center For The Arts At The Armory",
    "Center For The Arts Of Bonita Springs",
    "Center For The Arts of Homer",
    "Central Park Performing Arts Center",
    "Cervantes' Other Side",
    "Chain Reaction",
    "Cine El Rey Theatre",
    "Brown County Playhouse",
    "City Winery Philadelphia",
    "City Winery Washington DC",
    "Classic Q's",
    "Hard Rock Cafe",
    "Cohoes Music Hall",
    "Colony Woodstock",
    "Comedy Club At The Stardome",
    "Commodore Barry Club",
    "Company Theatre",
    "Conduit",
    "Constellation Room @ The Observatory",
    "Coppell Arts Center",
    "Cornerstone",
    "Coushatta Casino Resort",
    "Cypress",
    "Da Playground",
    "Dada Dallas",
    "Dante's",
    "Darkstar",
    "Daryl's House",
    "Diana Wortham Theatre",
    "Diesel Concert Theater",
    "District Live",
    "Downtown Music Hall",
    "Eastside Bowl",
    "El Club",
    "Empire Underground",
    "Exit/In",
    "F.M. Kirby Center For Perf. Arts - Chandelier Lobby",
    "Fiesta Showroom At Harrah's",
    "Fort Frenzy",
    "Freight And Salvage",
    "Fruitlands Museum",
    "Full Circle Brewing Co.",
    "Funny Bone Comedy Club & Restaurant",
    "Furnace 41",
    "Gabe's",
    "Gallo Center for the Arts - Foster Family Theater",
    "Garver Feed Mill",
    "Garver Feed Mill",
    "Goldfield Trading Post",
    "Grand Opera House Of The South",
    "Grand Theatre",
    "Great American Music Hall",
    "Greenwich Odeum",
    "Grog Shop",
    "Ground Zero Blues Club",
    "Growlers",
    "Hangar Theatre",
    "Hard Rock Cafe",
    "Hard Rock Cafe",
    "Hard Rock Cafe",
    "Harlow's",
    "HI-FI",
    "High Dive",
    "High Noon Saloon",
    "Higher Ground - Showcase Lounge",
    "Hilarities",
    "Hobart Art Theater",
    "Hobby Center For The Performing Arts",
    "Holocene",
    "HopMonk Tavern",
    "House Of Blues - Cambridge Room",
    "HQ",
    "Madame Lou's",
    "Infinity Hall Hartford",
    "Infinity Hall Norfolk",
    "It'll Do Nightclub",
    "Jaeb Theatre",
    "Jake's Sports Cafe & Backroom",
    "Jeanne Rimsky Theater At Landmark On Main Street",
    "Jimmy’s Jazz And Blues Club",
    "Kirkland Performance Center",
    "Knitting Factory Brooklyn",
    "Knitting Factory NoHo",
    "Lafayette's Music Room",
    "Lamp Theatre",
    "Lark Hall",
    "Last Exit Live",
    "Laugh Out Loud! Comedy Club",
    "Launchpad",
    "Levitate Backyard",
    "Levity Live",
    "Lexington Village Theatre",
    "Life Community Church",
    "Lincoln Theatre",
    "Liquid Joe's",
    "Livermore Valley Performing Arts Center",
    "Lobo Theater",
    "Lodge Room",
    "Lone Tree Arts Center",
    "Los Globos",
    "Lovedraft's Brewing Co.",
    "Madison Live",
    "Magooby's Joke House",
    "Mahall's",
    "Marin Center Showcase Theatre",
    "Market Hotel",
    "Marquis Theater",
    "McKinney Performing Arts Center",
    "McMenamins Lola's",
    "McMenamins Mission Theater",
    "Meow Wolf Santa Fe",
    "Metropolis Performing Arts Center",
    "Miami Improv Comedy Theater",
    "Milk & Honey Ciders",
    "Miramar Theatre",
    "Mississippi Studios",
    "Moe's Alley",
    "Montalvo Arts Center - Carriage House Theatre",
    "Motorco Music Hall",
    "Moxi Theater",
    "Nectar Lounge",
    "Musica",
    "Musical Instrument Museum",
    "Mystic Theatre",
    "Narrows Center for the Arts",
    "Neck Of The Woods",
    "Nelson Family Vineyards",
    "Neurolux",
    "New Brookland Tavern",
    "Newberry Opera House",
    "Ocean Mist",
    "Oddbody's Music Room",
    "Off Broadway Nightclub",
    "Offbeat Hideout",
    "Old Coupland Inn And Dancehall",
    "One Church",
    "One Eyed Jacks",
    "Ontario Improv Comedy Club",
    "Ophelia's Electric Soapbox",
    "Ottobar",
    "The Basement East",
    "Parx Casino",
    "Peace Center - Gunter Theatre",
    "Pie Shop DC",
    "Planet Trog",
    "Polsky Theatre",
    "Portland House Of Music",
    "Prairie Center For The Arts",
    "Preserving Hardcore",
    "Proud Larry's",
    "Pub Rock Live",
    "Purgatory At The Masquerade",
    "Putters & Gutters",
    "Race Street Live",
    "Raleigh Improv",
    "Rams Head On Stage",
    "Rec Room",
    "recordBar",
    "Respectable Street",
    "Revival Music Hall",
    "Rialto Theater",
    "Richmond Music Hall At Capital Ale House",
    "Rickshaw Stop",
    "Ridgefield Playhouse",
    "Ridley's Comedy Castle",
    "Rockbox Theatre",
    "RockHouse Bar & Grill",
    "Rockin' Rodeo",
    "Rose Music Hall",
    "Rustix Pub",
    "S.O.B.'S",
    "Saint Rocke",
    "Sam's Burger Joint Music Hall",
    "San Jose Improv",
    "Saturn",
    "Schrott Center For The Arts",
    "Scott Recital Hall",
    "Scottish Rite Masonic Museum & Library",
    "Sellersville Theater 1894",
    "Seminole Casino Hollywood",
    "Shalin Liu Performance Center",
    "Shank Hall",
    "Side Splitters Comedy Club",
    "Silverado Saloon",
    "Skylight Opera Theatre",
    "Lincoln Hall",
    "SLO BREW",
    "Smith's Olde Bar",
    "Reggies Rock Club",
    "Soiled Dove Underground",
    "Old Town School Of Folk Music",
    "Songbirds Guitar Museum",
    "Sonia",
    "City Winery NYC",
    "Soreng Theatre",
    "Subterranean",
    "Soundcheck",
    "Soundcheck Studios",
    "South Omaha's Finest Tequila Garage Bar",
    "South Orange Performing Arts Ctr.",
    "South Point Hotel & Casino",
    "Space Ballroom",
    "Spirit",
    "Spokane Comedy Club",
    "Empty Bottle",
    "Stage On Herr",
    "Stand Up Live",
    "Stanley's Famous Pit Barbecue",
    "Star Theater",
    "Starline Social Club",
    "Stateside At The Paramount",
    "Stoughton Opera House",
    "Strand Theater",
    "Strummer's",
    "Studio Theater At The Tobin Center",
    "Sleeping Village",
    "Suffolk Theater",
    "Sweetwater Music Hall",
    "Tangent Gallery",
    "Martyrs'",
    "The 04 Center",
    "The 8X10",
    "The Abbey",
    "The Annex @ The Red Zone",
    "The Ark",
    "The ArtsCenter",
    "The Atlantis",
    "The Atrium",
    "The Back Room @ Colectivo",
    "The Basement",
    "The Birchmere",
    "The Black Box",
    "The Bluebird",
    "The Bottleneck",
    "The Bourbon Room Hollywood",
    "The Cannery Bar And Grill",
    "The Center For Arts In Natick",
    "The Chapel",
    "The Club At Stage AE",
    "The Club Kona",
    "The Coach House Concert Hall",
    "The Concert Lounge",
    "The Crafthouse Stage & Grill",
    "The Crystal Ballroom At Somerville Theatre",
    "The Domino Room",
    "The Echo",
    "The Egyptian Theatre",
    "The Emerson Theater",
    "The Event Gallery At Bethel Woods Center For The Arts",
    "The Flying Monkey Movie House & Performance Center",
    "The Foundry",
    "The Get Down",
    "The Guild Theatre",
    "The Holding Company",
    "The Improv",
    "The Improv",
    "The Improv",
    "The Improv",
    "The Improv Comedy Club & Restaurant",
    "The Intersection / The Stache",
    "The Liberty",
    "Spy Bar",
    "The Loud",
    "The Lyric Theatre",
    "The Magic Bag",
    "The Maverick",
    "The Meadows",
    "The Miracle Theater",
    "The Miracle Theatre",
    "The Mishawaka Presents 2454 West",
    "The Montage Music Hall",
    "The Music Box",
    "City Winery Chicago",
    "The New Parish",
    "The Old Church Concert Hall",
    "The Olympic",
    "The Oncenter - Carrier Theater",
    "The Outland",
    "The Outland Ballroom",
    "The Outpost",
    "The Paramount",
    "The Parish",
    "The Parish At House Of Blues",
    "The Pub Station Taproom",
    "The Pyramid Scheme",
    "The Range",
    "The Rebel Lounge",
    "The Red Room Lounge",
    "The Rex Theatre",
    "The Riff",
    "Maurer Concert Hall",
    "The Roxy Theatre",
    "The Roxy Theatre",
    "The Sanctuary",
    "The Shea Theater Arts Center",
    "The Social",
    "The Space",
    "The Tarkington Theater",
    "The Underground",
    "The Vanguard",
    "The Vera Project",
    "The Visulite Theatre",
    "The Whirling Tiger",
    "The Winchester Music Tavern",
    "The Windjammer",
    "The Woodshed",
    "The Woodward Opera House",
    "Theatre On The Square",
    "Thunderbird Music Hall",
    "Tin Roof Orlando",
    "Top Cat's",
    "Toulouse Theatre",
    "Tower Theatre",
    "Tractor Tavern",
    "Transplants Brewing Company",
    "Troubadour",
    "Turf Club",
    "Ukie Club",
    "Union Stage",
    "Uptown! Knauer Performing Arts Center",
    "Urban Lounge",
    "Vinyl",
    "Vitalidad Movement Arts & Events Center (VMAC)",
    "VIVO Live Music",
    "Warehouse Live - Studio",
    "Westhampton Beach Performing Arts Center",
    "Whisky A Go Go",
    "Wild Buffalo House Of Music",
    "Wildey Theatre",
    "Wiley's Tavern",
    "Willie's Joint",
    "Wonder Bar",
    "World Cafe Live - Downstairs",
    "Yak & Yeti",
    "Yolo Nightclub",
    "Yoshi's Oakland",
    "Zanzabar",
    "Zebulon",
    "Zilkha Hall"
]

venues_2 = ["Growlers",
    "Hangar Theatre",
    "Hard Rock Cafe",
    "Hard Rock Cafe",
    "Hard Rock Cafe",
    "Harlow's",
    "HI-FI",
    "High Dive",
    "High Noon Saloon",
    "Higher Ground - Showcase Lounge",
    "Hilarities",
    "Hobart Art Theater",
    "Hobby Center For The Performing Arts",
    "Holocene",
    "HopMonk Tavern",
    "House Of Blues - Cambridge Room",
    "HQ",
    "Madame Lou's",
    "Infinity Hall Hartford",
    "Infinity Hall Norfolk",
    "It'll Do Nightclub",
    "Jaeb Theatre",
    "Jake's Sports Cafe & Backroom",
    "Jeanne Rimsky Theater At Landmark On Main Street",
    "Jimmy’s Jazz And Blues Club",
    "Kirkland Performance Center",
    "Knitting Factory Brooklyn",
    "Knitting Factory NoHo",
    "Lafayette's Music Room",
    "Lamp Theatre",
    "Lark Hall",
    "Last Exit Live",
    "Laugh Out Loud! Comedy Club",
    "Launchpad",
    "Levitate Backyard",
    "Levity Live",
    "Lexington Village Theatre",
    "Life Community Church",
    "Lincoln Theatre",
    "Liquid Joe's",
    "Livermore Valley Performing Arts Center",
    "Lobo Theater",
    "Lodge Room",
    "Lone Tree Arts Center",
    "Los Globos",
    "Lovedraft's Brewing Co.",
    "Madison Live",
    "Magooby's Joke House",
    "Mahall's",
    "Marin Center Showcase Theatre",
    "Market Hotel",
    "Marquis Theater",
    "McKinney Performing Arts Center",
    "McMenamins Lola's",
    "McMenamins Mission Theater",
    "Meow Wolf Santa Fe",
    "Metropolis Performing Arts Center",
    "Miami Improv Comedy Theater",
    "Milk & Honey Ciders",
    "Miramar Theatre",
    "Mississippi Studios",
    "Moe's Alley",
    "Montalvo Arts Center - Carriage House Theatre",
    "Motorco Music Hall",
    "Moxi Theater",
    "Nectar Lounge",
    "Musica",
    "Musical Instrument Museum",
    "Mystic Theatre",
    "Narrows Center for the Arts",
    "Neck Of The Woods",
    "Nelson Family Vineyards",
    "Neurolux",
    "New Brookland Tavern",
    "Newberry Opera House",
    "Ocean Mist",
    "Oddbody's Music Room",
    "Off Broadway Nightclub",
    "Offbeat Hideout",
    "Old Coupland Inn And Dancehall",
    "One Church",
    "One Eyed Jacks",
    "Ontario Improv Comedy Club",
    "Ophelia's Electric Soapbox",
    "Ottobar",
    "The Basement East",
    "Parx Casino",
    "Peace Center - Gunter Theatre",
    "Pie Shop DC",
    "Planet Trog",
    "Polsky Theatre",
    "Portland House Of Music",
    "Prairie Center For The Arts",
    "Preserving Hardcore",
    "Proud Larry's",
    "Pub Rock Live",
    "Purgatory At The Masquerade",
    "Putters & Gutters",
    "Race Street Live",
    "Raleigh Improv",
    "Rams Head On Stage",
    "Rec Room",
    "recordBar",
    "Respectable Street",
    "Revival Music Hall",
    "Rialto Theater",
    "Richmond Music Hall At Capital Ale House",
    "Rickshaw Stop",
    "Ridgefield Playhouse",
    "Ridley's Comedy Castle",
    "Rockbox Theatre",
    "RockHouse Bar & Grill",
    "Rockin' Rodeo",
    "Rose Music Hall",
    "Rustix Pub",
    "S.O.B.'S",
    "Saint Rocke",
    "Sam's Burger Joint Music Hall",
    "San Jose Improv",
    "Saturn",
    "Schrott Center For The Arts",
    "Scott Recital Hall",
    "Scottish Rite Masonic Museum & Library",
    "Sellersville Theater 1894",
    "Seminole Casino Hollywood",
    "Shalin Liu Performance Center",
    "Shank Hall",
    "Side Splitters Comedy Club",
    "Silverado Saloon",
    "Skylight Opera Theatre",
    "Lincoln Hall",
    "SLO BREW",
    "Smith's Olde Bar",
    "Reggies Rock Club",
    "Soiled Dove Underground",
    "Old Town School Of Folk Music",
    "Songbirds Guitar Museum",
    "Sonia",
    "City Winery NYC",
    "Soreng Theatre",
    "Subterranean",
    "Soundcheck",
    "Soundcheck Studios",
    "South Omaha's Finest Tequila Garage Bar",
    "South Orange Performing Arts Ctr.",
    "South Point Hotel & Casino",
    "Space Ballroom",
    "Spirit",
    "Spokane Comedy Club",
    "Empty Bottle",
    "Stage On Herr",
    "Stand Up Live",
    "Stanley's Famous Pit Barbecue",
    "Star Theater",
    "Starline Social Club",
    "Stateside At The Paramount",
    "Stoughton Opera House",
    "Strand Theater",
    "Strummer's",
    "Studio Theater At The Tobin Center",
    "Sleeping Village",
    "Suffolk Theater",
    "Sweetwater Music Hall",
    "Tangent Gallery",
    "Martyrs'",
    "The 04 Center",
    "The 8X10",
    "The Abbey",
    "The Annex @ The Red Zone",
    "The Ark",
    "The ArtsCenter",
    "The Atlantis",
    "The Atrium",
    "The Back Room @ Colectivo",
    "The Basement",
    "The Birchmere",
    "The Black Box",
    "The Bluebird",
    "The Bottleneck",
    "The Bourbon Room Hollywood",
    "The Cannery Bar And Grill",
    "The Center For Arts In Natick",
    "The Chapel",
    "The Club At Stage AE",
    "The Club Kona",
    "The Coach House Concert Hall",
    "The Concert Lounge",
    "The Crafthouse Stage & Grill",
    "The Crystal Ballroom At Somerville Theatre",
    "The Domino Room",
    "The Echo",
    "The Egyptian Theatre",
    "The Emerson Theater",
    "The Event Gallery At Bethel Woods Center For The Arts",
    "The Flying Monkey Movie House & Performance Center",
    "The Foundry",
    "The Get Down",
    "The Guild Theatre",
    "The Holding Company",
    "The Improv",
    "The Improv",
    "The Improv",
    "The Improv",
    "The Improv Comedy Club & Restaurant",
    "The Intersection / The Stache",
    "The Liberty",
    "Spy Bar",
    "The Loud",
    "The Lyric Theatre",
    "The Magic Bag",
    "The Maverick",
    "The Meadows",
    "The Miracle Theater",
    "The Miracle Theatre",
    "The Mishawaka Presents 2454 West",
    "The Montage Music Hall",
    "The Music Box",
    "City Winery Chicago",
    "The New Parish",
    "The Old Church Concert Hall",
    "The Olympic",
    "The Oncenter - Carrier Theater",
    "The Outland",
    "The Outland Ballroom",
    "The Outpost",
    "The Paramount",
    "The Parish",
    "The Parish At House Of Blues",
    "The Pub Station Taproom",
    "The Pyramid Scheme",
    "The Range",
    "The Rebel Lounge",
    "The Red Room Lounge",
    "The Rex Theatre",
    "The Riff",
    "Maurer Concert Hall",
    "The Roxy Theatre",
    "The Roxy Theatre",
    "The Sanctuary",
    "The Shea Theater Arts Center",
    "The Social",
    "The Space",
    "The Tarkington Theater",
    "The Underground",
    "The Vanguard",
    "The Vera Project",
    "The Visulite Theatre",
    "The Whirling Tiger",
    "The Winchester Music Tavern",
    "The Windjammer",
    "The Woodshed",
    "The Woodward Opera House",
    "Theatre On The Square",
    "Thunderbird Music Hall",
    "Tin Roof Orlando",
    "Top Cat's",
    "Toulouse Theatre",
    "Tower Theatre",
    "Tractor Tavern",
    "Transplants Brewing Company",
    "Troubadour",
    "Turf Club",
    "Ukie Club",
    "Union Stage",
    "Uptown! Knauer Performing Arts Center",
    "Urban Lounge",
    "Vinyl",
    "Vitalidad Movement Arts & Events Center (VMAC)",
    "VIVO Live Music",
    "Warehouse Live - Studio",
    "Westhampton Beach Performing Arts Center",
    "Whisky A Go Go",
    "Wild Buffalo House Of Music",
    "Wildey Theatre",
    "Wiley's Tavern",
    "Willie's Joint",
    "Wonder Bar",
    "World Cafe Live - Downstairs",
    "Yak & Yeti",
    "Yolo Nightclub",
    "Yoshi's Oakland",
    "Zanzabar",
    "Zebulon",
    "Zilkha Hall"
]
venues_list_part1 = [
    "3rd And Lindsley Nashville", "1720", "24 Oxford @ Virgin Hotels Las Vegas", "24-7 Entertainment",
    "2720 Cherokee Performing Arts Center", "45 East", "Academy Of Music Theatre", "Admiral Theatre",
    "Aggie Theatre", "Aladdin Theater", "Albany Municipal Auditorium", "Andiamo Celebrity Showroom",
    "Angel Of The Winds Casino Resort", "Anthem At Hard Rock Hotel & Casino", "Antone's",
    "Appalachian Theatre of the High Country", "Arcada Theatre", "Arcata Theatre Lounge", "Ardmore Music Hall",
    "Argyros Performing Arts Center", "Aria Ballroom @ MGM Springfield", "Arlington Music Hall", "Armadillo Palace",
    "Artie's Bar & Grill", "Artis--Naples", "Asbury Lanes", "Asheville Music Hall", "Ashland Armory", "AURA",
    "Authentic Life Church", "Banita Creek Hall", "Bankhead Theater", "Bardavon, 1869 Opera House", "Barre Opera House",
    "Barrelhouse Ballroom", "Barrelhouse Brewing Company", "Barrymore Theatre", "Beer City Music Hall", "Belding Theater",
    "Believe Music Hall", "Belle Mehus Auditorium", "Belly Up", "Beverly O'Neill Theater", "Big Top Brewing Company",
    "Big Top Chautauqua", "Bigs Bar", "Bijou Theatre", "Bilheimer Capitol Theatre", "Bimbo's 365 Club", 
    "Bing Crosby Theater", "Black Cat", "Blue Ocean Music Hall", "Bluebird Nightclub", "Bomhard Theater"
]

venues_list_part2 = [
    "Bossanova Ballroom", "Bourbon Theatre", "Brewskeez Smokehouse & Music", "Brewsky's", "Brooklyn Bowl", 
    "Brooklyn Bowl Philadelphia", "Brooklyn Monarch", "Broward Center Amaturo Theater", "Buskirk-Chumley Theater", 
    "Cahn Auditorium", "Capital Turnaround", "Capitol Theater", "Carlisle Theatre", "Cat's Cradle", "Celine",
    "Central Baptist Church", "Chelsea's", "El Corazon", "Christian Life Cathedral", "Circle Square Cultural Center",
    "Cisco Brewers", "City Winery Atlanta", "City Winery Hudson Valley / Outdoors", "CityChurch San Antonio", 
    "Clayton Opera House", "Club LA", "Colonial Theatre", "Colonial Theatre", "Colonial Theatre", "Colonial Theatre",
    "Come And Take It Live", "Cornerstone Church Of Clarion", "Cowboy's", "Crest Theatre", "City Winery Nashville", 
    "Culture Room", "Cumberland Caverns", "Del Norte Tacos", "Delmar Hall", "Deluxe", "Des Plaines Theatre", 
    "Discopussy", "Discovery Theatre", "DNA Lounge", "Don Quixote", "Door County Auditorium", "Dothan Opera House",
    "Dream Peoria", "Eagles Theatre", "EchoPlex", "Edgewater Christian Fellowship", "Edmonds Center For The Arts",
    "Egyptian Theatre", "Eichelberger Performing Arts Center", "El Rey Theatre", "Eldorado Showroom at Eldorado Hotel & Casino",
    "Electric Playhouse", "Elevation 27", "Elsewhere", "Emerson Center", "Empress Theatre", "Fargo Brewing Company", 
    "Fargo Theatre", "Fete Music Hall", "Fine Line", "First Baptist Church", "First Baptist Church", 
    "First Baptist Church Of Fairhope", "Five Flags Theater", "Fletcher Opera Theater", "Fox Theatre", "Fremont Theater",
    "Furniture Factory Bar & Grill", "Garden Amphitheatre", "George's Majestic Lounge", "Gerald C. Wilson Auditorium",
    "Gold Strike Casino Resort", "Goldfield Trading Post", "Gothic Theatre", "Grace Baptist Church", "Graceland Baptist Church"
]

venues_list_part3 = [
    "Granite Peak Ski Area", "Ground Zero", "Gruene Hall", "GST Studios", "Hangar 1819", "Hank's Texas Grill", 
    "Hanna Theatre", "Hard Rock Cafe", "Hard Rock Cafe", "Hargray Capitol Theatre", "Harvester Performance Center", 
    "Hawthorne Theatre", "Headliners Music Hall", "Hell At The Masquerade", "Illsley Ball Nordstrom Recital Hall", 
    "Heritage Center Theatre", "High Point Theatre", "Higher Ground", "Honky Tonk Texas", "Hooligans Music Hall", 
    "Hopkins Center For The Arts", "House Of Blues", "House Of Independents", "Immanuel Church", "Impact Christian Church",
    "Imperial Theatre", "Improv Comedy Club and Dinner Theatre", "INVY Nightclub", "Irvine Barclay Theatre", 
    "James Lumber Performing Arts Center", "Jax Underbelly", "Jefferson Theater", "Jergels Rhythm Grille", 
    "Jimmy's Jazz And Blues Club", "Jo Ann Davidson Theatre", "John Van Duzer Theatre", "JW Marriott Hotel", "Karma",
    "KiMo Theatre", "Kingdom NIghtclub", "Kitty Carlisle Hart Theatre", "Knitting Factory Concert House", 
    "Knitting Factory Hollywood", "Landis Theater", "Larcom Performing Arts Theatre", "Last Concert Cafe", 
    "Leland City Club", "Lensic Performing Arts Center", "Lesher Center for the Arts", "Lexington Opera House", 
    "Lexington's Cary Memorial Hall", "Liberty Theatre", "Life Austin", "Fourth Presbyterian Church", "Lincoln Theatre", 
    "Lincoln Theatre", "Lobero Theatre", "Thalia Hall", "Lowbrow Palace", "Lucky Eagle Casino", "Madison Center For The Arts", 
    "Magnolia Church", "Mainstage", "Majestic Fort Smith", "Majestic Theater Perf. Arts Center", "Majestic Theatre"
]

venues_list_part4 = [
    "Marathon Center For The Performing Arts", "Marathon Church", "Marines Memorial Theatre", "Athenaeum Theatre", 
    "Mary Jane Teall Theater", "Maryland Hall For The Creative Arts", "Park Community Church", 
    "McMenamins Spanish Ballroom At Elk Temple", "Mémoire At Encore Boston Harbor", "Memorial Hall OTR", 
    "Mercury Ballroom", "Mesa Theater", "Metro Music Hall", "Metropolitan Church Of God", "Metropolitan Theatre", 
    "Mexia High School Auditorium", "Mickey's Black Box", "Middle East Restaurant & Nightclub Downstairs", 
    "Midnight Rodeo", "Adler Hall At The New York Society for Ethical Culture", 
    "Millennium Theatre At Gold Strike Casino Resort", "Miners Foundry Cultural Center", "Mississippi Moon Bar", "Mohawk",
    "Mountainview Christian Church", "Mr. Small's Theatre", "Murray Hill Theatre", "Music Box", "Music Farm", 
    "Music Hall Of Williamsburg", "Nashua Center For The Arts", "National Hispanic Cultural Center", "Neumos", 
    "Neighborhood Theatre", "North Shore Ctr. For The Perf. Arts", "Oaklawn Racing & Gaming", "Oceanside Event Center", 
    "Old Rock House", "Avondale Music Hall", "O'Neals Sportsbar And Grill", "Orpheum Theatre", 
    "Palace Of Fine Arts Theatre", "Palace Theatre", "Palladium Theater At St. Petersburg College", "Q Nightclub", 
    "Pappy And Harriet's Pioneertown Palace", "Paradise Nightclub & Restaurant", "Paradise Rock Club", "Paramount Bristol", 
    "Logan Square Auditorium", "Parkway Church On The Mountain", "Parkway Fellowship", "Pathway Church", 
    "Patricia Reser Center For The Arts", "Peoples Bank Theatre", "Performing Arts Center At White Knolls High School", 
    "PK Ice House", "Plaza Live Orlando", "Ponte Vedra Concert Hall", "Potosi Live", "Preserving Underground", 
    "Preston Arts Center", "Le Poisson Rouge", "Bottom Lounge", "Range 231 N", "Red River Station Bbq", "Chop Shop"
]

venues_list_part5 = [
    "Reif Performing Arts Center", "Republic NOLA", "Revolution Hall", "Revolution Music Room", "Rick's Cafe", 
    "Rio Theatre", "Rock City Church", "Rockharbor", "The Gramercy Theatre", "Rogue Theatre", "Roof Garden Ballroom", 
    "Route 66 Motorheads", "The Bowery Ballroom", "Saenger Theatre", "Schroeder Hall", "Sound Bar", "Scottish Rite Theatre", 
    "Scottsdale Ctr. For The Perf. Arts", "Scout Bar", "Seminole Hard Rock Hotel & Casino Tampa", "Sessions Music Hall", 
    "Shea Center for Performing Arts", "Sheldon Concert Hall", "Showroom At Turning Stone Casino Resort", "Skully's Music Diner",
    "Slowdown", "Soka University - Performing Arts Center", "SoundWell SLC", "St. Andrews Hall", "Stage 722", 
    "Stage West - State College", "State Theatre", "The Country Music Hall Of Fame And Museum", "Stone Pony", "Strand Theatre", 
    "Strings Music Festival", "Strings Music Pavilion", "Supernova", "Sugar Loaf Performing Arts Center", "Superior Ingredients"
]

venues_500_1000 = venues_list_part1 + venues_list_part2 + venues_list_part3 + venues_list_part4 + venues_list_part5
